#!/bin/bash

COUNT=0
while [ 1 ]; do
	echo "################# RUN # ${COUNT} ######################"
	./poller 10.5.16.2 1337
	if [ $? -ne 0 ]; then
		exit
	fi
	echo
	echo
	echo
	COUNT=$((COUNT + 1))
	sleep 2
done
